version: '3'

networks:
  app-tier:
    driver: bridge

services:
  mysqldb:
    image: 'docker.io/bitnami/mysql:8.0'
    ports:
      - '3306:3306'
    expose:
      - 3306
    #volumes:
    #  - mysql_data:/Users/unbxd/Documents/drone-spring-app/drones-db/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=unbxd
      - MYSQL_PASSWORD=Unbxd@123
      - MYSQL_DATABASE=drones_info
    networks:
      - app-tier


  myapp:
    image: 'drone-details:v1'
    container_name: drone-details-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysqldb
      - DB_USERNAME=unbxd
      - DB_PASSWORD=Unbxd@123
      - DRONES_DB=drones_info
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
    networks:
      - app-tier
    command: >
      bash -c './wait-for-it.sh -h mysqldb -p 3306 -t 20; java -jar drones-spring-0.0.1-SNAPSHOT.jar'