apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: drone-app
build:
  local:
    concurrency: 0
    push: false
    useDockerCLI: true
  tagPolicy:
#    sha256: {}
    envTemplate:
      template: "{{.TAG}}"
  artifacts:
    - image: drone-details
      docker:
        dockerfile: Dockerfile

deploy:
  helm:
    releases:
    - name: drone-helm-app
      chartPath: helm
      setValues:
        service.type: ClusterIP
      artifactOverrides:
        image: drone-details
      valuesFiles:
        - helm/values.yaml
portForward:
  - resourceType: deployment
    resourceName: drone-helm-app
    port: 8080
    localPort: 8080
