From openjdk:11
copy ./target/drones-spring-0.0.1-SNAPSHOT.jar drones-spring-0.0.1-SNAPSHOT.jar
copy ./scripts/wait-for-it.sh wait-for-it.sh
#copy ./start.sh
#CMD []
#CMD ["java", "-jar", "drones-spring-0.0.1-SNAPSHOT.jar"]
