apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      volumes:
        - name: init-scripts
#          Did not add directly from hostpath as it means node path. kind node should have the file
#          hostPath:
#            # directory location on host
#            path: /Users/unbxd/Documents/drones-spring-project/scripts
#            # this field is optional
#            type: Directory
          configMap:
            name: init-scripts-cfg-map
            items:
              - key: setup.sql
                path: setup.sql
              - key: wait-for-it.sh
                path: wait-for-it.sh
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          volumeMounts:
            - mountPath: /home/worker/scripts/
              name: init-scripts
              readOnly: true
          command: [ 'sh', '-c', "/home/worker/scripts/wait-for-it.sh -h drone-mysql.default.svc.cluster.local -p 3306 -t 30" ]
      containers:
        - name: db-setup
          image: 'docker.io/bitnami/mysql:8.0'
          command: ["sh", "-c", "/home/worker/scripts/wait-for-it.sh -h drone-mysql.default.svc.cluster.local -p 3306 -t 30 && mysql -hdrone-mysql.default.svc.cluster.local -uunbxd -pUnbxd@123 < /home/worker/scripts/setup.sql;"]
          volumeMounts:
            - mountPath: /home/worker/scripts
              name: init-scripts
              readOnly: true