version: '2'

networks:
  app-tier:
    driver: bridge

services:
  mysql:
    image: 'docker.io/bitnami/mysql:8.0'
    ports:
      - '3306:3306'
    #volumes:
    #  - mysql_data:/Users/unbxd/Documents/drone-spring-app/drones-db/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=unbxd
      - MYSQL_PASSWORD=Unbxd@123
      - MYSQL_DATABASE=drones_info
    networks:
      - app-tier
#  myapp:
#    image: 'drone-spring:v2'
#    networks:
#      - app-tier