name: DronesWiki

on:
  push:
    branches:
      - devops
  pull_request:
    branches:
      - devops

jobs:
  build:
    if: github.repository == 'portkey2112/DronesWiki'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        id: setup-java
        uses: actions/setup-java@v1
        with:
            java-version: 11
            distribution: 'temurin'
            cache: maven

      - name: Build with Maven
        id: build-application
        run: |
          cd $GITHUB_WORKSPACE
          ./mvnw clean package -DskipTests -Dassembly.skipAssembly=true
          
      - name: Run Docker container
        id: build-container
        run: docker-compose up